
def level_tx(level):
    
    if level == 'infantil':
        text = "O aluno da Educação Infantil, geralmente com idades entre 0 e 5 anos, está em uma fase crucial do desenvolvimento integral, onde aspectos cognitivos, emocionais, sociais e motores são fortemente moldados. Nessa etapa, o aprendizado ocorre principalmente por meio de experiências sensoriais, brincadeiras, interação social e exploração do ambiente, o que estimula a curiosidade e a criatividade. As principais dificuldades enfrentadas por esses alunos incluem a compreensão e regulação emocional, adaptação às primeiras rotinas escolares e desenvolvimento da linguagem, habilidades motoras finas e noções iniciais de convivência em grupo. Por isso, o apoio de professores, famílias e um ambiente estimulante são essenciais para favorecer um desenvolvimento equilibrado e positivo."
    elif level == 'fudamental1':
        text = 'O aluno do Ensino Fundamental I, com idades entre 6 e 10 anos, está em uma etapa de transição importante, onde o foco do aprendizado passa a incluir habilidades mais formais, como a leitura, a escrita e a matemática, ao mesmo tempo em que se aprofundam competências sociais e emocionais. É um período marcado pela curiosidade e pela vontade de explorar o mundo, mas também pela necessidade de apoio para desenvolver concentração, organização e autonomia nos estudos. As principais dificuldades podem incluir o processo de alfabetização, a assimilação de conceitos abstratos e a interação social, pois começam a surgir conflitos e desafios na convivência em grupo. Nessa fase, o suporte de professores e famílias, aliado a metodologias ativas e motivadoras, é fundamental para garantir o engajamento e o sucesso no aprendizado.'
    elif level == 'fudamental2':
        text = 'O aluno do Ensino Fundamental II, geralmente com idades entre 11 e 14 anos, vive um período de intensas transformações físicas, emocionais e sociais, marcadas pela entrada na pré-adolescência. Nessa etapa, o aprendizado se torna mais complexo e diversificado, com a introdução de disciplinas específicas que exigem o desenvolvimento do pensamento crítico, lógico e reflexivo. Os alunos começam a construir maior autonomia nos estudos e a relacionar os conteúdos escolares com o mundo ao seu redor. Entre as dificuldades mais comuns estão a gestão do tempo, a adaptação ao aumento da carga de responsabilidades, os desafios das relações interpessoais e as oscilações emocionais características da idade. Um ambiente educativo acolhedor, aliado a estratégias pedagógicas que incentivem a participação ativa e o diálogo, é essencial para apoiar o desenvolvimento integral do aluno nessa fase.'
    elif level == 'medio':
        text = 'O aluno do Ensino Médio, geralmente entre 15 e 17 anos, está em uma etapa de consolidação acadêmica e preparação para a vida adulta, enfrentando desafios relacionados ao futuro profissional, à escolha de carreira e à autonomia. Nessa fase, o aprendizado é mais aprofundado e estruturado, exigindo habilidades analíticas, reflexivas e de síntese, além de maior capacidade de organização e disciplina. Paralelamente, os jovens vivenciam transformações emocionais e sociais significativas, muitas vezes enfrentando pressão por resultados e tomada de decisões importantes. Entre as dificuldades comuns estão o gerenciamento do estresse, a manutenção do foco e do engajamento em meio a distrações, e a necessidade de relacionar os conteúdos escolares com os contextos da vida prática. O papel do educador é fundamental, não apenas como transmissor de conhecimento, mas também como orientador, ajudando o aluno a desenvolver competências socioemocionais, pensamento crítico e autonomia para lidar com os desafios acadêmicos e pessoais.'
    elif level == 'graduacao':
        text = 'O aluno de graduação no Ensino Superior, geralmente com idades entre 18 e 24 anos, embora possa incluir faixas etárias mais amplas, está em uma fase de formação especializada, buscando consolidar conhecimentos teóricos e práticos em sua área de interesse. Essa etapa é marcada pela autonomia no aprendizado, exigindo habilidades como organização, pensamento crítico, capacidade de pesquisa e aplicação prática do conhecimento. Paralelamente, os alunos enfrentam desafios como adaptação ao ambiente universitário, gestão do tempo entre estudos, trabalho e vida pessoal, além da pressão para atender expectativas acadêmicas e projetar um futuro profissional. A interação com professores, colegas e a inserção em atividades práticas, como estágios e projetos, são fundamentais para o desenvolvimento acadêmico e pessoal, preparando-os para o mercado de trabalho e para a atuação cidadã.'
    elif level == 'posgraduacao':
        text = 'O aluno de pós-graduação no Ensino Superior, seja em nível de especialização, mestrado ou doutorado, está em busca de aprofundamento e especialização em uma área de conhecimento específica. Geralmente mais maduro, com idades variando amplamente, este aluno já possui uma formação acadêmica consolidada e frequentemente combina os estudos com atividades profissionais. O aprendizado é centrado na pesquisa, na produção de conhecimento e na aplicação prática, exigindo autonomia, disciplina, capacidade de análise crítica e habilidades avançadas de escrita e comunicação acadêmica. Entre os desafios mais comuns estão o equilíbrio entre vida profissional, pessoal e acadêmica, a pressão por produtividade intelectual e a gestão de projetos complexos, como a elaboração de uma dissertação ou tese. A interação com orientadores, pares e redes acadêmicas, assim como o acesso a recursos e infraestrutura adequados, é essencial para o sucesso nessa fase de formação avançada.'
    elif level == 'executiva':
        text = 'O aluno de educação executiva é, geralmente, um profissional experiente, em posições de liderança ou aspirante a cargos estratégicos, buscando desenvolver habilidades específicas para enfrentar desafios complexos no ambiente corporativo. Este perfil valoriza o aprendizado aplicado, com foco em estratégias, liderança, inovação e tomada de decisão, frequentemente dentro de contextos de mercado dinâmicos e globais. Com agendas intensas, esses alunos enfrentam o desafio de conciliar os estudos com responsabilidades profissionais e pessoais, demandando flexibilidade no formato das aulas e alta relevância nos conteúdos. A educação executiva é marcada por metodologias práticas, como estudos de caso, simulações e projetos, além de uma forte ênfase em networking, criando um ambiente de troca de experiências e aprendizado colaborativo entre profissionais de diferentes setores.'
    elif level == 'outras':
        text = 'O aluno de modalidades alternativas de educação, como educação profissionalizante, corporativa, inclusiva ou a distância, pode ter idades bastante diversas, variando de jovens buscando qualificação inicial a adultos em busca de aprimoramento ou reconversão profissional. Esse perfil é marcado pela busca de aprendizado prático, dinâmico e personalizado, muitas vezes orientado por objetivos específicos, como entrar no mercado de trabalho, se adaptar a novas tecnologias ou adquirir competências específicas. As principais dificuldades enfrentadas incluem conciliar os estudos com responsabilidades pessoais e profissionais, adaptar-se a formatos de ensino não convencionais, como o digital, ou superar barreiras estruturais, como o acesso limitado a recursos tecnológicos ou educacionais. Por isso, essas modalidades de educação demandam flexibilidade, metodologias aplicadas e suporte contínuo para garantir a inclusão, o engajamento e o sucesso dos alunos.'
    else:
        text = ''

    return text